name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # Assumes releases are created from main
          fetch-depth: 0

      - name: Check initial git status
        run: |
          echo "Initial git status after checkout:"
          git status --porcelain
          echo "Current version in lerna.json:"
          cat lerna.json | grep version
          echo "Current version in package.json files:"
          head -n 5 packages/*/package.json | grep -A1 "==>" | grep -E "(==>|version)"

      - uses: actions/setup-node@v4
        with:
          node-version: '23'

      - uses: oven-sh/setup-bun@v2

      - name: 'Setup npm for npmjs'
        run: |
          npm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Protobuf Compiler
        run: sudo apt-get install -y protobuf-compiler

      - name: Install dependencies
        run: bun install

      - name: Reset any installation changes
        run: |
          # Reset any lock file changes from installation
          git checkout -- bun.lock || true
          # Show current git status for debugging
          echo "Git status after install:"
          git status --porcelain

      - name: Commit any remaining changes from install
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes to commit
          if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "Committing changes from install step..."
            git add -A
            git commit -m "chore: temporary commit for install changes" || true
          else
            echo "No changes to commit"
          fi

      - name: Check format
        run: bun run format:check

      - name: Run lint
        run: bun run lint

      - name: Update Package Versions
        id: version
        run: |
          # Get version from the release tag that triggered the workflow
          LATEST_TAG=${{ github.ref_name }}
          VERSION=${LATEST_TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "Updating all packages to version: $VERSION"
          # Update versions in all package.json files WITHOUT publishing
          # The --amend flag allows modifying the last commit if needed
          npx lerna version $VERSION --exact --yes --no-git-tag-version --no-push --force-publish --amend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: |
          echo "Building packages with version: ${{ env.VERSION }}"
          bun run build && bun run build:docs

      - name: Publish Packages
        id: publish
        run: |
          echo "Publishing version: ${{ env.VERSION }}"
          # Publish the already-built packages
          npx lerna publish from-package --yes --dist-tag latest --no-private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and Push Version Bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add **/package.json lerna.json
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No version changes to commit."
          else
            git commit -m "chore(release): bump versions to v${{ env.VERSION }}"
            git push origin main
          fi

      - name: Create Pull Request to develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base "develop" \
            --head "main" \
            --title "Release: Sync main to develop for v${{ env.VERSION }}" \
            --body "Syncs version bump from main to develop." \
            --label "1.x"
